name: "github-action-pr-slack-reminder"
description: "Send reminders with pull requests that need reviews and that are ready to be merged."
branding:
  color: blue
  icon: at-sign
inputs:
  aws-region:
    description: 'Region in which the Github <=> Slack engineer mapping JSON is stored'
    required: true
  aws-s3-bucket:
    description: 'Bucket in which the Github <=> Slack engineer mapping JSON object is stored in S3'
    required: true
  aws-s3-object-key:
    description: 'Name of the Github <=> Slack users mapping JSON object in S3'
    required: true
  bot-token:
    description: "OAuth token for your Slack App Bot to sign requests to Slack's API with."
    required: true
  channel-id:
    description: "ID of the channel or conversation in Slack you would like messages posted to."
    required: true
  github-token:
    description: "Personal access token with repository rights."
    required: true
  exclude-label:
    description: "If you would like to ignore pull requests with this label."
    required: false
    default: ""
  older-than:
    description: "If you would like to take into account only pull requests that were updated in the last n days."
    required: false
  slack-block-title:
    description: "If you would like to set a title for the slack block."
    required: false
  
runs:
  using: "node20"
  main: "dist/index.js"
