/* eslint-disable quotes */
export const messages = [
  "Rise and shine, devs! Today's challenge: help us review these pull requests so we can all bask in the glory of successful merges. ☀️👨‍💻👩‍💻",
  "Hey there, beautiful people! Let's make someone's day and review their pull request.They're counting on us! 💖💻",
  "Good morning, sleepyheads! There's no better way to start the day than with a fresh cup of coffee and a review of some pull requests. 👀👨‍💻👩‍💻",
  "It's time to review some pull requests and show our fellow developers some love! Remember, it's like holding the door open for someone, but with code. 😜🚪💻",
  "Calling all superheroes! We need your powers of review to save these pull requests from the dreaded land of limbo. Let's get them merged and make the world a better place! 🦸‍♂️🦸‍♀️👨‍💻👩‍💻",
  "Rise and grind, coding warriors! The battlefield is full of pull requests that need reviewing, and we're the only ones who can bring peace and harmony to the merge conflicts. 💪👨‍💻👩‍💻",
  "Attention all developers! Our pull request garden needs some watering, so let's give them some reviews and watch them bloom into successful merges. 🌷💻",
  "Wakey wakey, eggs and code! Let's review some pull requests and make the day brighter for everyone. Because let's face it, there's nothing like a successful merge to put a smile on your face. 🌞😃👨‍💻👩‍💻",
  "It's time to channel our inner detectives and review some pull requests. Let's solve these merge conflicts and bring justice to the code. 🔍🕵️‍♂️🕵️‍♀️💻",
  "Good morning, team! Let's make sure these pull requests don't feel like they're stranded on a deserted island. They need our help to make it to merge paradise. 🏝️👨‍💻👩‍💻",
  "Rise and shine, my fellow developers! We have some pull requests that need your expert eyes on them. Don't leave them hanging like a forgotten Christmas stocking - give them some love and let's get these babies merged! 😎👨‍💻👩‍💻",
  "Rise and shine, code wizards! It's time to wield your power of review and bring balance to the force of pull requests. 🧙‍♂️🧙‍♀️💻",
  "Good morning, code monkeys! Let's swing into action and review some pull requests like the agile primates we are. 🐒👨‍💻👩‍💻",
  "Rise and grind, code warriors! It's time to face the enemy of unmerged pull requests and emerge victorious. 💪👨‍💻👩‍💻",
  "Hey there, code samurais! The battlefield of pull requests needs your expert eye, so let's sharpen our swords of review and take on the challenge. 🗡️👨‍💻👩‍💻",
  "Good morning, coding superheroes! Today's mission, should you choose to accept it, is to review some pull requests and save the world from the tyranny of unmerged code. 🦸‍♂️🦸‍♀️💻",
  'Attention, code connoisseurs! We have some fine pull requests that need your palate of review to truly appreciate their full flavor. Bon appétit! 🍷🧀💻',
  "Rise and shine, coding ninjas! Let's use our stealthy review skills to slay the dragon of unmerged pull requests and claim the treasure of successful merges. 🐲💰👨‍💻👩‍💻",
  "Good morning, code astronauts! We're ready to launch some pull requests into the merge stratosphere, but we need your expert navigation to make it a successful mission. 🚀👨‍💻👩‍💻",
  'Attention, code explorers! We have some uncharted pull requests that need your fearless review to pave the way for a successful merge journey. 🌍👨‍💻👩‍💻',
  "Rise and shine, code alchemists! Let's take the base metals of unmerged pull requests and transform them into the gold of successful merges. 🧪💰💻",
  "Good morning, coding unicorns! Let's sprinkle some magic on these pull requests and turn them into successful merges. 🦄✨👨‍💻👩‍💻",
  'Attention, code chefs! We have some pull requests that need your expert recipe of review to whip them up into a tasty merge. 🍲👨‍💻👩‍💻',
  "Rise and shine, code adventurers! Let's set sail on the sea of pull requests and chart a course to successful merges. ⛵🗺️👨‍💻👩‍💻",
  'Good morning, code therapists! We have some pull requests that need your expert listening skills to hear their merge conflicts and find a resolution. 🧘‍♂️🧘‍♀️💻',
  'Attention, code Olympians! The race to successful merges is on, and we need your expert speed and agility to cross the finish line. 🏃‍♂️🏃‍♀️🏆👨‍💻👩‍💻',
  "Rise and shine, code dragons! Let's unleash our fiery review skills and turn these pull requests into the gold of successful merges. 🐉🔥💰💻",
  "Good morning, code wizards! Let's use our magic wand of review to turn these unmerged pull requests into successful spells of code. 🧙‍♂️🧙‍♀️🔮💻",
  'Attention, code warriors! We have some pull requests that need your battle-tested review skills to emerge victorious from the merge conflicts. 🗡️🛡️👨‍💻👩‍💻',
  "Rise and shine, code champions! Let's bring our A-game of review and turn these pull requests into successful merges worthy of a victory lap. 🏆👨‍💻👩‍💻",
  "Good morning, code artists! Let's use our expert eye for detail to review these pull requests and turn them into masterpieces of merged code. 🎨👨‍💻👩‍💻",
  'Attention, code detectives! We have some pull requests that need your expert investigative skills to uncover the truth behind their merge conflicts. 🔍🕵️‍♂️🕵️‍♀️💻',
  "Rise and shine, code gladiators! Let's enter the arena of pull requests and fight for successful merges with our expert review skills. 🗡️🛡️👨‍💻👩‍💻",
  'Good morning, code doctors! We have some pull requests that need your expert diagnosis of review to prescribe the perfect treatment for their merge conflicts. 🩺💊👨‍💻👩‍💻',
  'Attention, code architects! We have some pull requests that need your expert blueprint of review to design the perfect merge for our codebase. 🏗️📐💻',
  "Rise and shine, code astronauts! Let's take a giant leap for successful merges and use our expert review skills to navigate the zero-gravity of pull requests. 🚀👨‍💻👩‍💻",
  'Good morning, code pilots! We have some pull requests that need your expert flight plan of review to soar to successful merges. 🛫👨‍💻👩‍💻',
  'Attention, code magicians! We have some pull requests that need your expert illusion of review to turn the chaos of merge conflicts into the order of successful merges. 🎩🧙‍♂️🧙‍♀️💻',
  "Rise and shine, code superheroes! Let's use our powers of review to save the world from the evil of unmerged pull requests and bring peace to the codebase. 🦸‍♂️🦸‍♀️💻",
  'Good morning, code climbers! We have some pull requests that need your expert gear of review to scale the mountain of merge conflicts and reach the summit of successful merges. 🧗‍♂️🧗‍♀️🏔️💻',
  'Attention, code magistrates! We have some pull requests that need your expert judgment of review to deliver the verdict of successful merges. 👨‍⚖️👩‍⚖️💻',
  'Attention, code wizards! We have some pull requests that need your magic of review to make successful merges happen. 🧙‍♂️🧙‍♀️💻',
  "Rise and shine, code champions! Let's tackle the day's pull requests with our expert review skills and achieve successful merges. 🏆👨‍💻👩‍💻",
  'Good morning, code warriors! We have some pull requests that need your expert sword of review to slay the dragons of merge conflicts and achieve successful merges. ⚔️🐉👨‍💻👩‍💻',
  'Attention, code chefs! We have some pull requests that need your expert recipe of review to cook up some successful merges. 🍳👨‍🍳👩‍🍳💻',
  "Rise and shine, code ninjas! Let's use our stealthy review skills to sneak past the merge conflicts and achieve successful merges. 🥷👨‍💻👩‍💻",
  'Good morning, code adventurers! We have some pull requests that need your expert map of review to navigate the treacherous terrain of merge conflicts and reach the treasure of successful merges. 🗺️🧭👨‍💻👩‍💻',
  'Attention, code captains! We have some pull requests that need your expert helm of review to steer the ship of our codebase towards successful merges. ⛵🧭👨‍💻👩‍💻',
  "Rise and shine, code champions! Let's enter the arena of pull requests and use our review skills to achieve victory through successful merges. 🏟️🎖️👨‍💻👩‍💻",
  'Good morning, code alchemists! We have some pull requests that need your expert formula of review to turn the lead of merge conflicts into the gold of successful merges. 🔬🧪💰👨‍💻👩‍💻',
  'Attention, code explorers! We have some pull requests that need your expert compass of review to guide us through the wilderness of merge conflicts and reach the oasis of successful merges. 🧭🌵🐫👨‍💻👩‍💻',
  'Good morning, code wizards! Pull requests await your review magic. ✨🔮👨‍💻👩‍💻',
  "Hey code heroes! It's time to review some pull requests and make our codebase even more awesome! 💪🏻💻👨‍🔬👩‍🔬",
  "Rise and shine, code geniuses! Let's make our codebase better by reviewing these pull requests. 🌞📈💻👨‍💻👩‍💻",
  'Good morning, code warriors! Pull requests need your review to win the battle against merge conflicts. ⚔️🛡️👨‍💻👩‍💻',
  'Attention, code wizards! Pull requests need your spell of review to create successful merges. 🧙‍♂️🧙‍♀️👨‍💻👩‍💻',
  "Rise and shine, code heroes! Let's give these pull requests the review they deserve and make our codebase even more amazing! 💪🏻💻🚀👨‍💻👩‍💻",
  "Good morning, code ninjas! It's time to review some pull requests and slice through the merge conflicts. 🥷🗡️💻👨‍💻👩‍💻",
  'Hey code wizards! The power of review is needed to merge these pull requests successfully. 🧙‍♂️🧙‍♀️👨‍💻👩‍💻',
  "Rise and shine, code superheroes! Let's use our super review powers to make these pull requests successful merges. 🦸‍♂️🦸‍♀️💻👨‍💻👩‍💻",
  'Good morning, code masters! Pull requests need your expert review to achieve successful merges. 🧐👨‍🏫👩‍🏫💻👨‍💻👩‍💻',
  "Good morning, code warriors! It's time to sharpen your review skills and conquer the pull request backlog. ⚔️👨‍💻👩‍💻",
  'Attention, code mavens! These pull requests need your expert review to ensure successful merges. 🧐💻🔍',
  'Hey code wizards! The power of your review skills can turn these pull requests into amazing merges. 🧙‍♂️🧙‍♀️💻🚀',
  'Rise and shine, code heroes! These pull requests are waiting for your heroic review to make them successful merges. 💪🏻🦸‍♂️🦸‍♀️💻',
  'Good morning, code champions! Your review skills are needed to make these pull requests victorious merges. 🏆💻👨‍💻👩‍💻',
  'Attention, code masters! These pull requests need your wise review to achieve successful merges. 🤓👨‍🏫👩‍🏫💻',
  'Hey code wizards! Your magical review can turn these pull requests into successful merges. 🧙‍♂️🧙‍♀️💻🪄',
  "Rise and shine, code ninjas! It's time to review these pull requests and show your stealthy merge skills. 🥷🤫💻",
  'Good morning, code geniuses! Your review expertise can turn these pull requests into epic merges. 🧠💡💻👨‍💻👩‍💻',
  'Attention, code wizards! These pull requests are in need of your magical review to make them amazing merges. 🧙‍♂️🧙‍♀️💻🌟',
  'Hey code heroes! The power of your review can turn these pull requests into successful merges. 💪🏻🛡️💻👨‍💻👩‍💻',
  "Rise and shine, code warriors! It's time to review these pull requests and conquer the merge conflicts. ⚔️🛡️💻👨‍💻👩‍💻",
  'Good morning, code wizards! Your magical review skills can turn these pull requests into successful merges. 🧙‍♂️🧙‍♀️💻🔮',
  'Attention, code champions! These pull requests need your championship-level review to become successful merges. 🏆👑💻',
  'Hey code masters! These pull requests need your masterful review to achieve successful merges. 👨‍🏫👩‍🏫💻🎓',
  'Rise and shine, code heroes! Your review skills are needed to turn these pull requests into victorious merges. 💪🏻🦸‍♂️🦸‍♀️💻',
  "Good morning, code warriors! It's time to review these pull requests and merge them like true warriors. ⚔️👨‍💻👩‍💻",
  'Attention, code wizards! These pull requests need your magical review to become amazing merges. 🧙‍♂️🧙‍♀️💻🌟',
  'Hey code champions! Your review expertise can turn these pull requests into epic merges. 🏆💡💻👨‍💻👩‍💻',
  'Rise and shine, code ninjas! These pull requests need your stealthy review to become successful merges. 🥷🤫💻',
  'Good morning, code geniuses! These pull requests are in need of your genius review to become successful merges. 🧠💻👨‍💻👩‍💻',
  "Attention, code wizards! It's time to work your magic and review these pull requests into successful merges. 🧙‍♂️🧙‍♀️💻🔮",
  'Hey code heroes! The success of these pull requests depends on your expert review skills. 💪🏻🦸‍♂️🦸‍♀️💻',
  'Rise and shine, code warriors! These pull requests need your valiant review to achieve successful merges. ⚔️🛡️💻👨‍💻👩‍💻',
  'Good morning, code wizards! Your magical touch is needed to review these pull requests into successful merges. 🧙‍♂️🧙‍♀️💻🌟',
  'Attention, code champions! Your expert review skills can turn these pull requests into victorious merges. 🏆💻👨‍💻👩‍💻',
  'Hey code masters! These pull requests are in need of your masterful review to become successful merges. 👨‍🏫👩‍🏫💻📚',
  'Rise and shine, code heroes! Your review skills are the key to unlock the successful merge of these pull requests. 🔑💻👨‍💻👩‍💻',
  'Good morning, code warriors! These pull requests need your brave review to face the merge challenges. ⚔️🛡️💻👨‍💻👩‍💻',
  'Attention, code wizards! Your review skills can turn these pull requests into magical merges. 🧙‍♂️🧙‍♀️💻🪄',
  'Hey code champions! Your championship-level review can turn these pull requests into successful merges. 🏆💻👨‍💻👩‍💻',
  "Rise and shine, code ninjas! It's time to sneak into these pull requests and make them successful merges. 🥷🕵️‍♂️💻",
  'Good morning, code geniuses! These pull requests need your genius-level review to become successful merges. 🧠💻👨‍💻👩‍💻',
  'Attention, code wizards! Your magical review is needed to turn these pull requests into successful merges. 🧙‍♂️🧙‍♀️💻🔮',
  'Hey code heroes! These pull requests need your heroic review to overcome the merge conflicts. 💪🏻🦸‍♂️🦸‍♀️💻',
  'Rise and shine, code warriors! Your review skills are needed to make these pull requests successful merges. ⚔️🛡️💻👨‍💻👩‍💻',
  'These pull requests need a hero like you to save the day! 🦸‍♂️🦸‍♀️',
  "Reviewing pull requests is like a box of chocolates. You never know what you're gonna get. 🍫👨‍💻👩‍💻",
  "Don't let these pull requests gather dust. Let's get reviewing! 🌪️💨👨‍💻👩‍💻",
  "Your expertise is needed! Let's review these pull requests and get them merged! 🤓👨‍💻👩‍💻",
  'These pull requests are like plants. They need your review to grow and blossom! 🌱🌺👨‍💻👩‍💻',
  "It's time to review some pull requests and kick some code butt! 🦵💥👨‍💻👩‍💻",
  "The only thing these pull requests are missing is your review! Let's get to it! 👨‍💻👩‍💻💪",
  'Want to be a superhero? Review these pull requests and save the codebase! 🦸‍♂️🦸‍♀️💥👨‍💻👩‍💻',
  "Ready to flex your code review muscles? Check out these pull requests and let's get to work! 💪👨‍💻👩‍💻",
  "These pull requests are patiently waiting for your review. Let's not keep them waiting any longer! 🕰️⏳👨‍💻👩‍💻",
  'Your code review skills are needed! These pull requests are calling your name. 👨‍💻👩‍💻📞',
  "It's time to put on your code review hat and get to work on these pull requests! 🧐👨‍💻👩‍💻",
  "These pull requests need some love and attention. Let's give them the review they deserve! ❤️💻👨‍💻👩‍💻",
  "These pull requests are like puzzle pieces. Let's review them and put the codebase back together! 🧩👨‍💻👩‍💻",
  "Do you hear that? It's the sound of these pull requests begging for your review! Let's do this! 🙏👨‍💻👩‍💻",
  "Don't be a stranger to these pull requests. Let's review them and get them merged! 👋👨‍💻👩‍💻",
  'Want to make a difference? Review these pull requests and help make the codebase even better! 👨‍💻👩‍💻🌟',
  "These pull requests need some TLC (tender loving code-review). Let's give them the attention they deserve! ❤️👨‍💻👩‍💻",
  "Reviewing these pull requests is like being a detective. Let's investigate the code and get to the bottom of it! 🕵️‍♂️🕵️‍♀",
  "Let's not leave these pull requests hanging. They need your review to move forward! 🤝👨‍💻👩‍💻",
  "These pull requests are like diamonds in the rough. Let's review them and bring out their brilliance! 💎👨‍💻👩‍💻",
  "The codebase needs your expertise! Let's review these pull requests and make it even better! 🤓👨‍💻👩‍💻",
  "Don't let these pull requests get lost in the shuffle. Review them and let's get them merged! 📥🔄📤👨‍💻👩‍💻",
  "These pull requests are like a puzzle waiting to be solved. Let's review them and put the pieces together! 🧩👨‍💻👩‍💻",
  "Let's show these pull requests some love with a thoughtful review! 💜👨‍💻👩‍💻",
  "We're so close to merging these pull requests! Let's review and get them across the finish line! 🏁👨‍💻👩‍💻",
  "Don't let these pull requests collect dust. Let's review them and keep the codebase shining! ✨👨‍💻👩‍💻",
  "These pull requests are begging for your attention. Let's review and give them the green light! 🟢👨‍💻👩‍💻",
  "Reviewing these pull requests is like taking a walk in the park. Let's enjoy the process and get some fresh air! 🌳👨‍💻👩‍💻",
  "These pull requests are knocking on the door. Let's review and welcome them in! 🚪👨‍💻👩‍💻",
  "It's time to flex your code review muscles! Let's review these pull requests and show off our skills! 💪👨‍💻👩‍💻",
  "These pull requests are like a gift waiting to be unwrapped. Let's review and discover what's inside! 🎁👨‍💻👩‍💻",
  "Don't leave these pull requests hanging. Let's review and get them merged into the codebase! 🤝👨‍💻👩‍💻",
  "These pull requests are full of potential. Let's review and unlock their value! 💰👨‍💻👩‍💻",
  "Don't let these pull requests gather cobwebs. Let's review and keep the codebase tidy! 🕸️👨‍💻👩‍💻",
  "These pull requests are waiting for your expert review. Let's dive in and make the code even better! 🤓👨‍💻👩‍💻",
  "Let's give these pull requests the VIP treatment they deserve with a prompt review! 🎖️👨‍💻👩‍💻",
  "These pull requests are like a delicious dish waiting to be savored. Let's review and enjoy every bite! 🍴👨‍💻👩‍💻",
  "It's review time! Let's take a look at these pull requests and make the codebase shine! 💡👨‍💻👩‍💻",
  "Don't leave these pull requests stranded. Let's review and help them reach their destination! 🛣️👨‍💻👩‍💻",
  "These pull requests are a testament to our collaborative spirit. Let's review and keep the momentum going! 🤝👨‍💻👩‍💻",
  "Don't let these pull requests feel lonely. Let's review and give them some company in the codebase! 👥👨‍💻👩‍💻",
  "These pull requests are like a garden waiting to bloom. Let's review and watch the codebase flourish! 🌻👨‍💻👩‍💻",
  "Reviewing these pull requests is like solving a mystery. Let's dig in and uncover the truth! 🔎👨‍💻👩‍💻",
  "It's time to review and conquer these pull requests like brave warriors of code! ⚔️👨‍💻👩‍💻",
  "Let's give these pull requests a Hollywood-style review and make them feel like movie stars! 🎥👨‍💻👩‍💻",
  "These pull requests are like a box of chocolates waiting to be discovered. Let's review and savor every flavor! 🍫👨‍💻👩‍💻",
  "Don't let these pull requests turn into vampires that suck the life out of our codebase. Let's review and slay them! 🧛‍♂️🦇👨‍💻👩‍💻",
  "These pull requests are like a rollercoaster ride waiting to happen. Let's review and enjoy the thrill! 🎢👨‍💻👩‍💻",
  "Don't let these pull requests feel like they're stuck in a traffic jam. Let's review and give them a green light! 🚦👨‍💻👩‍💻",
  "Let's show these pull requests some love and attention, like the neglected plants in our office. 🌿👨‍💻👩‍💻",
  "These pull requests are like a good book waiting to be read. Let's review and get lost in the story! 📚👨‍💻👩‍💻",
  "Don't let these pull requests be like a Netflix series that you can't stop watching. Let's review and bring them to an end! 🎬👨‍💻👩‍💻",
  "These pull requests are like a puzzle waiting to be solved. Let's review and fit the pieces together! 🧩👨‍💻👩‍💻",
  "Let's give these pull requests the review they deserve, like a Michelin-starred restaurant! 🍽️👨‍💻👩‍💻",
  "Don't let these pull requests be like a forgotten sock in the dryer. Let's review and give them a matching pair! 🧦🧦👨‍💻👩‍💻",
  "These pull requests are like the stars in the sky, waiting to be discovered. Let's review and explore the universe! ✨👨‍💻👩‍💻",
  "Let's review these pull requests like a coach who wants to bring out the best in their team. Go, team code! 🏋️‍♂️👨‍💻👩‍💻",
  "Don't let these pull requests be like a forgotten to-do list. Let's review and check off those tasks! ✅👨‍💻👩‍💻",
  "Let's review these pull requests like a detective who wants to solve the mystery. Who knows what treasures we'll find! 🕵️‍♂️🔎👨‍💻👩‍💻",
  "Don't let these pull requests be like a lonely planet in space. Let's review and bring them into orbit! 🪐🚀👨‍💻👩‍💻",
  "These pull requests are like a musical instrument waiting to be played. Let's review and create beautiful code harmonies! 🎶🎸👨‍💻👩‍💻",
  "Let's review these pull requests like a group of friends who want to make the most of their time together. Let's have fun while coding! 🎉👨‍💻👩‍💻",
  "Don't let these pull requests be like a puzzle with missing pieces. Let's review and complete the picture! 🧩🖼️👨‍💻👩‍💻",
  "These pull requests are like a delicious meal waiting to be savored. Let's review and enjoy the code feast! 🍽️👨‍💻👩‍💻",
  "Don't let these pull requests be like a book with unturned pages. Let's review and uncover the knowledge within! 📚🔍👨‍💻👩‍💻",
  "Let's review these pull requests like a gardener who wants to grow the best plants. Let's cultivate the code! 🌱👨‍💻👩‍💻",
  "These pull requests are like a treasure chest waiting to be opened. Let's review and discover the riches inside! 💰💎👨‍💻👩‍💻",
  "Don't let these pull requests be like a song stuck in your head. Let's review and bring the music to life! 🎵👨‍💻👩‍💻",
  "Let's review these pull requests like a captain who wants to steer their ship to success. Let's navigate the code! ⚓👨‍💻👩‍💻",
  "These pull requests are like a canvas waiting to be painted. Let's review and create a masterpiece! 🎨🖌️👨‍💻👩‍💻",
  "Don't let these pull requests be like a missed opportunity. Let's review and seize the chance to improve the code! 🚀👨‍💻👩‍💻",
  "Let's review these pull requests like a teacher who wants to inspire their students. Let's educate and learn from the code! 📚👨‍🏫👨‍💻👩‍💻",
  "These pull requests are like a recipe waiting to be cooked. Let's review and create a delicious code dish! 🍲👨‍💻👩‍💻",
  "Don't leave these pull requests unattended, they might throw a party without us! Let's review and join the fun 🎉👨‍💻👩‍💻",
  "Let's review these pull requests like a detective who wants to solve a mystery. Let's uncover the code clues 🔍🕵️‍♂️🕵️‍♀️",
  "These pull requests are like a workout waiting to be done. Let's review and flex our code muscles 💪👨‍💻👩‍💻",
  "Don't let these pull requests be like a traffic jam, let's review and clear the way for smoother code flow 🚦👨‍💻👩‍💻",
  "Let's review these pull requests like a chef who wants to spice things up. Let's add some flavor to the code! 🌶️👨‍🍳👨‍💻👩‍💻",
  "These pull requests are like a puzzle waiting to be solved. Let's review and put the code pieces together 🧩👨‍💻👩‍💻",
  "Don't let these pull requests be like a plant that withers without water. Let's review and nourish the code! 🌱💦👨‍💻👩‍💻",
  "Let's review these pull requests like a traveler who wants to explore new places. Let's journey through the code! ✈️🗺️👨‍💻👩‍💻",
  "These pull requests are like a story waiting to be told. Let's review and make it a tale of code greatness! 📖👨‍💻👩‍💻",
  "Don't let these pull requests be like a guitar without strings. Let's review and make beautiful code music! 🎸🎶👨‍💻👩‍💻",
];
